887 - Requested changes to the Historic Site Resource Details tab view
bcgov/BCHeritage_arches pull request #37
Opened 2024-06-12 22:21 UTC by jrods

Re: bcgov/BCHeritage#887

2024-06-13 03:10 UTC, bferguso requested changes
@jrods - Overall looks great. Seems like the changes to the urls.py that I made as part of the legislative acts change didn't make it into the cherry pick into this branch. Would you please merge that in and look at the codes suggestions?

2024-06-13 03:10 UTC, bferguso commented on src/bcrhp/bcrhp/media/js/viewmodels/bcrhp-site.js
> +        /*
Would you please remove this commented out code?

2024-06-13 03:10 UTC, bferguso commented on src/bcrhp/bcrhp/media/js/viewmodels/bcrhp-site.js
> +            console.log(`Getting authority for ID ${actId}`)
Would you please remove the console log statements?

2024-06-13 15:02 UTC, jrods commented
@bferguso I've updated the PR

2024-06-17 16:29 UTC, bferguso approved these changes

2024-06-17 17:12 UTC, merged