947 - Modify csv export on the historic site search results
bcgov/BCHeritage_arches pull request #38
Opened 2024-06-12 22:23 UTC by jrods

Re: bcgov/BCHeritage#947

2024-06-13 03:17 UTC, bferguso requested changes
@jrods - Would you please implement this as a (or multiple) migration(s), complete with the reverse migration? The SQL files in the `pkg/` directory only get run when a project is recreated, so we can't use it to patch an existing project.

2024-06-25 19:32 UTC, bferguso requested changes
Did all the existing materialized views need to be dropped and recreated? I looks like at least some of drop/recreate statements are redundant (eg mv_borden_number - not sure how many others)- we should only necessary changes in the migration and not touch the objects that aren't modified. This will keep QA and changes more localized and easier to digest.

When first running this w/ 1500 records it took quite a while to run. Once the SQL is trimmed down to what is actually changing we can have a look to see where we can improve performance.

2024-06-25 19:32 UTC, bferguso commented on src/bcrhp/bcrhp/pkg/business_data/resource_views/0002_create_onerow_view.sql
>                                                    __arches_get_concept_label(unnest(functional_state));
Please roll back any changes or additions made in the `pkg/business_data/resource_views` directory - these will never be run so all updates should happen in the migrations directory.

2024-06-25 19:32 UTC, bferguso commented on src/bcrhp/bcrhp/pkg/business_data/resource_views/0004_historic_public_site_view.sql
> +drop view if exists databc.V_HISTORIC_ENVIRO_ONEROW_SITE;
Please roll back any changes or additions made in the `pkg/business_data/resource_views` directory - these will never be run so all updates should happen in the migrations directory.

2024-06-25 19:32 UTC, bferguso commented on src/bcrhp/bcrhp/search/search_export.py
> +                return super().to_csv(instance_results, instance_columns, name)
I'm getting an `instance_columns` is not defined message here. Should this be `columns`?

2024-06-25 19:32 UTC, bferguso commented on src/bcrhp/bcrhp/search/search_export.py
> +                print(instance_results[0])
Please remove debug print statements

2024-06-25 19:32 UTC, bferguso commented on src/bcrhp/bcrhp/views/search.py
> +    # print("In BCGOv specific search results")
This is probably leftover from my dirty code, but please remove the debug statements

2024-06-25 21:12 UTC, jrods commented
> Did all the existing materialized views need to be dropped and recreated? I looks like at least some of drop/recreate statements are redundant (eg mv_borden_number - not sure how many others)- we should only necessary changes in the migration and not touch the objects that aren't modified. This will keep QA and changes more localized and easier to digest.

I wasn't sure what is within the deployed databases. If everything that is in the resource_views/0002_create_onerow_view.sql is in fact on the deploys, I can cut out the statements that are not modified in the mig module.

> When first running this w/ 1500 records it took quite a while to run. Once the SQL is trimmed down to what is actually changing we can have a look to see where we can improve performance.

The original databc view before modifying was also about the same amount of run time, if I remembered correctly. I haven't done any analyzing of the hotspots yet but will have a look

2024-06-25 21:13 UTC, jrods commented on src/bcrhp/bcrhp/search/search_export.py
> +                print(instance_results[0])
oops, my bad, leftovers from a previous stash, fixed

2024-07-02 17:28 UTC, bferguso requested changes
@jrods - looking good so far! 
Please sort the export view by borden number and address the two changes requested below and then I think we're good to go. I'd like to do a a test of the DataBC view when we deliver to DLVR to ensure that the data looks the same.

2024-07-02 17:28 UTC, bferguso commented on src/bcrhp/bcrhp/migrations/947_historic_site_one_line.py
> +                , street_address as "Street Address"
For rows that can have a null value, please replace null value with empty string. Null values come out as "None" in the csv.

2024-07-02 17:28 UTC, bferguso commented on src/bcrhp/bcrhp/migrations/947_historic_site_one_line.py
> +                , authorities->>'registry_types' as "Registry Type"
Please make array values a semi-colon separated string.

2024-07-05 16:21 UTC, bferguso commented on src/bcrhp/bcrhp/migrations/947_historic_site_one_line.py
> +            drop procedure if exists refresh_materialized_views;
This procedure existed before to refresh the DataBC view. This should reinstate the previous version rather than dropping it.

2024-07-05 16:24 UTC, bferguso commented on src/bcrhp/bcrhp/migrations/947_historic_site_one_line.py
> +            drop view if exists databc.V_HISTORIC_ENVIRO_ONEROW_SITE cascade;
This needs to reinstate the previous version of this view.

2024-07-06 14:57 UTC, bferguso approved these changes

2024-07-06 14:57 UTC, merged